# Generated by Django 2.1.1 on 2018-10-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20181014_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank='true', verbose_name='date of birth'),
        ),
    ]
