# Generated by Django 2.1.1 on 2018-10-21 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 21, 14, 36, 44, 741404, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
