# Generated by Django 2.1.1 on 2018-10-21 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_posts_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published'),
        ),
    ]
