# Generated by Django 2.1.1 on 2018-10-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20181021_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
