# Generated by Django 2.0.7 on 2018-11-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20181025_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
