# Generated by Django 2.0.7 on 2018-11-05 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_comunity_comunityintrest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunityintrest',
            name='comunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunity', to='social.comunity'),
        ),
    ]
