# Generated by Django 2.1.3 on 2018-11-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date published'),
        ),
    ]
