# Generated by Django 2.1.3 on 2018-11-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_auto_20181107_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
